name: Checks
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: 20
          cache: "yarn"
      - run: yarn --immutable
      - run: yarn test

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: 20
          cache: "yarn"
      - run: yarn --immutable
      - run: yarn build
