name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build
        run: yarn build
      - name: Publish to NPM
        run: npm publish --provenance --access public
